const express = require('express')
const orderRouter = express.Router()
const orderController = require('../controllers/orderController')
const { auth } = require('../middleware/auth')
orderRouter.get('/testOrder', orderController.testOrder)
orderRouter.post('/addOrder', orderController.addOrder)
orderRouter.get('/getOrder', orderController.getOrder)
orderRouter.get('/getOrder/:id', orderController.getOrderById)
orderRouter.delete('/deleteOrder/:id', orderController.deleteOrder)
orderRouter.patch('/updateOrder/:id',  orderController.updateOrder)
orderRouter.get('/manyToOne',  orderController.manyToOne)
module.exports = orderRouter
