const express = require('express')
const transportRouter = express.Router()
const transportController = require('../controllers/transportController')
const { auth } = require('../middleware/auth')
transportRouter.get('/testTC', transportController.testTC)
transportRouter.post('/', auth, transportController.addTransports)
transportRouter.get('/', auth, transportController.getTranports)
transportRouter.get('/getTransportById/:id', auth, transportController.getTransportById)
transportRouter.delete('/:id', auth, transportController.deleteTransport)
transportRouter.patch('/:id', auth, transportController.updateTransport)
transportRouter.get('/query', auth, transportController.transportQuery)
module.exports = transportRouter
